from __future__ import annotations

from typing import Final

DEFAULT_TARGET_LANG: Final[str] = "en-US"
SUPPORTED_LANGUAGES: Final[dict[str, str]] = {
    "ACE": "Bahsa Acèh",
    "AF": "Afrikaans",
    "AN": "Aragonés",
    "AR": "العربية",
    "AS": "অসমীয়া",
    "AY": "Aymar aru",
    "AZ": "Azərbaycan dili",
    "BA": "Башҡортса",
    "BE": "Беларуская",
    "BG": "Български",
    "BHO": "भोजपुरी",
    "BN": "বাংলা",
    "BR": "Brezhoneg",
    "BS": "Bosanski",
    "CA": "Català",
    "CEB": "Cebuano",
    "CKB": "سۆرانی",
    "CS": "Čeština",
    "CY": "Cymraeg",
    "DA": "Dansk",
    "DE": "Deutsch",
    "EL": "Ελληνικά",
    "EN": "English",
    "EN-GB": "English (UK)",
    "EN-US": "English (US)",
    "EO": "Esperanto",
    "ES": "Español",
    "ES-419": "Español (Latinoamérica)",
    "ET": "Eesti",
    "EU": "Euskara",
    "FA": "فارسی",
    "FI": "Suomi",
    "FR": "Français",
    "GA": "Gaeilge",
    "GL": "Galego",
    "GN": "Guarani",
    "GOM": "कोंकणी",
    "GU": "ગુજરાતી",
    "HA": "Hausa",
    "HE": "עברית",
    "HI": "हिन्दी",
    "HR": "Hrvatski",
    "HT": "Kreyòl ayisyen",
    "HU": "Magyar",
    "HY": "Հայերեն",
    "ID": "Bahasa Indonesia",
    "IG": "Igbo",
    "IS": "Íslenska",
    "IT": "Italiano",
    "JA": "日本語",
    "JV": "Basa Jawa",
    "KA": "ქართული",
    "KK": "Қазақша",
    "KMR": "Kurmancî",
    "KO": "한국어",
    "KY": "Кыргызча",
    "LA": "Latina",
    "LB": "Lëtzebuergesch",
    "LMO": "Lumbaart",
    "LN": "Lingála",
    "LT": "Lietuvių",
    "LV": "Latviešu",
    "MAI": "मैथिली",
    "MG": "Malagasy",
    "MI": "Te Reo Māori",
    "MK": "Македонски",
    "ML": "മലയാളം",
    "MN": "Монгол",
    "MR": "मराठी",
    "MS": "Bahasa Melayu",
    "MT": "Malti",
    "MY": "မြန်မာဘာသာ",
    "NB": "Norsk bokmål",
    "NE": "नेपाली",
    "NL": "Nederlands",
    "OC": "Occitan",
    "OM": "Oromoo",
    "PA": "ਪੰਜਾਬੀ",
    "PAG": "Pangasinan",
    "PAM": "Kapampangan",
    "PL": "Polski",
    "PRS": "دری",
    "PS": "پښتو",
    "PT": "Português",
    "PT-BR": "Português (Brasil)",
    "PT-PT": "Português (Portugal)",
    "QU": "Runa Simi",
    "RO": "Română",
    "RU": "Русский",
    "SA": "संस्कृतम्",
    "SCN": "Sicilianu",
    "SK": "Slovenčina",
    "SL": "Slovenščina",
    "SQ": "Shqip",
    "SR": "Српски",
    "ST": "Sesotho",
    "SU": "Basa Sunda",
    "SV": "Svenska",
    "SW": "Kiswahili",
    "TA": "தமிழ்",
    "TE": "తెలుగు",
    "TG": "Тоҷикӣ",
    "TH": "ไทย",
    "TK": "Türkmençe",
    "TL": "Tagalog",
    "TN": "Setswana",
    "TR": "Türkçe",
    "TS": "Xitsonga",
    "TT": "Татарча",
    "UK": "Українська",
    "UR": "اردو",
    "UZ": "Oʻzbekcha",  # noqa: RUF001
    "VI": "Tiếng Việt",
    "WO": "Wolof",
    "XH": "isiXhosa",
    "YI": "ייִדיש",
    "YUE": "粵語",
    "ZH": "中文",
    "ZH-HANS": "简体中文",
    "ZH-HANT": "繁體中文",
    "ZU": "isiZulu",
}
